version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: oolio
      POSTGRES_PASSWORD: oolio_pass
      POSTGRES_DB: oolio_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres/data
