// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"github.com/khanghld27/kelvin-kart-challenge-api/app/internal/interface/persistence/rdbms/gormrepos"
	"github.com/khanghld27/kelvin-kart-challenge-api/app/internal/interface/restful/handlers"
	"github.com/khanghld27/kelvin-kart-challenge-api/app/internal/interface/restful/middleware"
	"github.com/khanghld27/kelvin-kart-challenge-api/app/internal/usecases/interactor"
	"github.com/khanghld27/kelvin-kart-challenge-api/pkg/gormer"
)

// Injectors from wire.go:

func TransactionMiddleware() middleware.TransactionMiddleware {
	dbAdapter := gormer.GetDB()
	txnDataSQL := gormrepos.NewTxnDataSQL(dbAdapter)
	transactionMiddleware := middleware.NewTransactionMiddleware(txnDataSQL)
	return transactionMiddleware
}

func ProductHandler() handlers.ProductHandler {
	productRepository := gormrepos.NewProductRepository()
	productUseCase := interactor.NewProductUseCase(productRepository)
	productHandler := handlers.NewProductHandler(productUseCase)
	return productHandler
}
